### ISSUE TITLE
opening 2 receivers using 2 different connections within the same process fails

### ISSUE THREAD

**Issue by jfromaniello** [amqp/rhea-promise#10]
**Describe the bug**
Opening a second receiver using a second connection in the same node.js process never completes.

**To Reproduce**
```javascript
const rhea = require('rhea-promise');

const connectionOptions = {
  username: 'guest',
  password: 'guest',
  host: 'localhost',
  port: 5672
};

(async function() {
  const connection1 = new rhea.Connection(connectionOptions);
  const connection2 = new rhea.Connection(connectionOptions);

  await connection1.open();
  console.log('opening sender1');
  await connection1.createSender({
    target: {
      address: 'test',
    },
  });
  console.log('sender1 is open');

  console.log('opening receiver1');
  await connection1.createReceiver({
    source: {
      dynamic: true,
    },
  });
  console.log('receiver1 is open');

  await connection2.open();

  console.log('opening receiver2');
  await connection2.createReceiver({
    source: {
      address: 'test',
    },
  })
  console.log('receiver2 is open');

  console.log('done');
  process.exit(0);
})();

```

**Expected behavior**
I will expect to see `done` in the console and the program terminating.

**Package-version**:  0.1.5
**node.js version**: v8.12.0
**OS name and version**: darwing/macos

**Additional context**
If I use the same connection object it works as expected.

**Comment by amarzavery** [comment]
@jfromaniello -  I would recommend setting the environment variable `export DEBUG=rhea*` and then run your script. This will provide more insights to what is happening under the hood.

Did couple of things.
- Modified the [receive.ts example](https://github.com/amqp/rhea-promise/blob/master/examples/receive.ts) in the repo to have something similar to what you have. You can find the updated example in a gist over [here](https://gist.github.com/amarzavery/5d12b12ce54a1f0375ddb7a43519d233). The example ran fine.
- Copy pasted the sample you provided and ran it as-is and now I see the problem. However, that is 
because it is not able to connect to localhost, since I haven't opened a server on localhost and that port number. It gets disconnected and attempts to reconnect and keeps on doing that over and over..

Here is the detailed log:
```bash
Amars-MBP:rhea-promise amarz$ node test.js
  rhea-promise:eventhandler [connection-1] rhea-promise 'connection' object is listening for events: [ 'connection_open', 'connection_close', 'connection_error', 'protocol_error', 'error', 'disconnected', 'settled', 'sender_error', 'sender_close', 'receiver_error', 'receiver_close', 'session_error', 'session_close' ] emitted by rhea's 'connection' object. +0ms
  rhea-promise:eventhandler [connection-2] rhea-promise 'connection' object is listening for events: [ 'connection_open', 'connection_close', 'connection_error', 'protocol_error', 'error', 'disconnected', 'settled', 'sender_error', 'sender_close', 'receiver_error', 'receiver_close', 'session_error', 'session_close' ] emitted by rhea's 'connection' object. +3ms
  rhea-promise:connection [connection-1] Trying to create a new amqp connection. +0ms
  rhea:reconnect [connection-1] Scheduled reconnect in 100ms +0ms
  rhea:events [connection-1] Connection got event: disconnected +0ms
  rhea-promise:connection [connection-1] connection got event: 'disconnected'. Re-emitting the translated context. +5ms
  rhea-promise:translate [connection-1] Translating the context for event: 'disconnected'. +0ms
  rhea-promise:error [connection-1] Error occurred while establishing amqp connection: { Error: connect ECONNREFUSED 127.0.0.1:5672
  rhea-promise:error     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
  rhea-promise:error   errno: 'ECONNREFUSED',
  rhea-promise:error   code: 'ECONNREFUSED',
  rhea-promise:error   syscall: 'connect',
  rhea-promise:error   address: '127.0.0.1',
  rhea-promise:error   port: 5672 } +0ms
{ Error: connect ECONNREFUSED 127.0.0.1:5672
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5672 }
  rhea:reconnect [connection-1] reconnecting... +105ms
  rhea:reconnect [connection-1] Scheduled reconnect in 200ms +2ms
  rhea:events [connection-1] Connection got event: disconnected +108ms
  rhea-promise:connection [connection-1] connection got event: 'disconnected'. Re-emitting the translated context. +108ms
  rhea-promise:translate [connection-1] Translating the context for event: 'disconnected'. +107ms
  rhea:reconnect [connection-1] reconnecting... +203ms
  rhea:reconnect [connection-1] Scheduled reconnect in 400ms +2ms
  rhea:events [connection-1] Connection got event: disconnected +204ms
  rhea-promise:connection [connection-1] connection got event: 'disconnected'. Re-emitting the translated context. +204ms
  rhea-promise:translate [connection-1] Translating the context for event: 'disconnected'. +204ms
  rhea:reconnect [connection-1] reconnecting... +402ms
  rhea:reconnect [connection-1] Scheduled reconnect in 800ms +2ms
  rhea:events [connection-1] Connection got event: disconnected +404ms
  rhea-promise:connection [connection-1] connection got event: 'disconnected'. Re-emitting the translated context. +404ms
  rhea-promise:translate [connection-1] Translating the context for event: 'disconnected'. +404ms
  rhea:reconnect [connection-1] reconnecting... +805ms
  rhea:reconnect [connection-1] Scheduled reconnect in 1600ms +2ms
  rhea:events [connection-1] Connection got event: disconnected +807ms
  rhea-promise:connection [connection-1] connection got event: 'disconnected'. Re-emitting the translated context. +807ms
  rhea-promise:translate [connection-1] Translating the context for event: 'disconnected'. +807ms
  rhea:reconnect [connection-1] reconnecting... +2s
  rhea:reconnect [connection-1] Scheduled reconnect in 3200ms +2ms
  rhea:events [connection-1] Connection got event: disconnected +2s
  rhea-promise:connection [connection-1] connection got event: 'disconnected'. Re-emitting the translated context. +2s
  rhea-promise:translate [connection-1] Translating the context for event: 'disconnected'. +2s
  rhea:reconnect [connection-1] reconnecting... +3s
  rhea:reconnect [connection-1] Scheduled reconnect in 6400ms +1ms
  rhea:events [connection-1] Connection got event: disconnected +3s
  rhea-promise:connection [connection-1] connection got event: 'disconnected'. Re-emitting the translated context. +3s
  rhea-promise:translate [connection-1] Translating the context for event: 'disconnected'. +3s
```
Do you want to try connecting to an actual service/endpoint? If possible please provide your debug logs. Please make sure to remove the password/secret if any that gets logged, before pasting the content over here.

**Comment by jfromaniello** [comment]
I am connecting to an actual service endpoint, is activemq running on my localhost:

```
» nc -z -v -w5 localhost 5672
localhost [127.0.0.1] 5672 (amqp) open
```

Here is the debug log running the test:
```
» DEBUG=rhea* node test.js
  rhea-promise:eventhandler [connection-1] rhea-promise 'connection' object is listening for events: [ 'connection_open', 'connection_close', 'connection_error', 'protocol_error', 'error', 'disconnected', 'settled', 'sender_error', 'sender_close', 'receiver_error', 'receiver_close', 'session_error', 'session_close' ] emitted by rhea's 'connection' object. +0ms
  rhea-promise:eventhandler [connection-2] rhea-promise 'connection' object is listening for events: [ 'connection_open', 'connection_close', 'connection_error', 'protocol_error', 'error', 'disconnected', 'settled', 'sender_error', 'sender_close', 'receiver_error', 'receiver_close', 'session_error', 'session_close' ] emitted by rhea's 'connection' object. +3ms
  rhea-promise:connection [connection-1] Trying to create a new amqp connection. +0ms
  rhea:io [connection-1] connected 127.0.0.1:58854 -> 127.0.0.1:5672 +0ms
  rhea:frames [connection-1] -> { protocol_id: 3, major: 1, minor: 0, revision: 0 } +0ms
  rhea:io [connection-1] read 42 bytes +12ms
  rhea:frames [connection-1] <- { protocol_id: 3, major: 1, minor: 0, revision: 0 } +12ms
  rhea:io [connection-1] got frame of size 34 +0ms
  rhea:raw [connection-1] RECV: 34 0000002202010000005340c01501e01202a305504c41494e09414e4f4e594d4f5553 +0ms
  rhea:frames [connection-1]:0 <- sasl_mechanisms#40 {"sasl_server_mechanisms":["PLAIN","ANONYMOUS"]}  +1ms
  rhea:frames [connection-1]:0 -> sasl_init#41 {"mechanism":"PLAIN","initial_response":{"type":"Buffer","data":[0,103,117,101,115,116,0,103,117,101,115,116]},"hostname":"localhost"}  +3ms
  rhea:raw [connection-1] SENT: 52 0000003402010000005341d00000002400000003a305504c41494ea00c006775657374006775657374a1096c6f63616c686f7374 +4ms
  rhea:io [connection-1] read 16 bytes +6ms
  rhea:io [connection-1] got frame of size 16 +0ms
  rhea:raw [connection-1] RECV: 16 0000001002010000005344c003015000 +2ms
  rhea:frames [connection-1]:0 <- sasl_outcome#44 {}  +2ms
  rhea:frames [connection-1] -> { protocol_id: 0, major: 1, minor: 0, revision: 0 } +1ms
  rhea:frames [connection-1]:0 -> open#10 {"username":"guest","password":"guest","host":"localhost","port":5672,"operationTimeoutInSeconds":60,"id":"connection-1","container_id":"920ac558-868c-c349-9181-f57a1e864bfb"}  +9ms
  rhea:raw [connection-1] SENT: 58 0000003a02000000005310d00000002a00000001a12439323061633535382d383638632d633334392d393138312d663537613165383634626662 +10ms
  rhea:io [connection-1] read 8 bytes +10ms
  rhea:frames [connection-1] <- { protocol_id: 0, major: 1, minor: 0, revision: 0 } +0ms
  rhea:io [connection-1] read 188 bytes +6ms
  rhea:io [connection-1] got frame of size 188 +1ms
  rhea:raw [connection-1] RECV: 188 000000bc02000000005310c0af0aa1096c6f63616c686f7374407000020000607fff7000003a984040e02302a30f414e4f4e594d4f55532d52454c41591044454c415945445f44454c495645525940c16b0aa30770726f64756374a1084163746976654d51a30c746f7069632d707265666978a108746f7069633a2f2fa30c71756575652d707265666978a10871756575653a2f2fa30776657273696f6ea106352e31352e36a308706c6174666f726da10a4a6176612f392e302e31 +7ms
  rhea:frames [connection-1]:0 <- open#10 {"container_id":"localhost","max_frame_size":131072,"channel_max":32767,"idle_time_out":15000,"offered_capabilities":["ANONYMOUS-RELAY","DELAYED_DELIVERY"],"properties":{"product":"ActiveMQ","topic-prefix":"topic://","queue-prefix":"queue://","version":"5.15.6","platform":"Java/9.0.1"}}  +7ms
  rhea:events [connection-1] Connection got event: connection_open +0ms
  rhea-promise:connection [connection-1] connection got event: 'connection_open'. Re-emitting the translated context. +50ms
  rhea-promise:translate [connection-1] Translating the context for event: 'connection_open'. +0ms
  rhea-promise:connection [connection-1] Resolving the promise with amqp connection. +1ms
opening sender1
  rhea-promise:eventhandler [connection-1] rhea-promise 'session' object is listening for events: [ 'session_open', 'session_error', 'session_close', 'settled', 'sender_error', 'sender_close', 'receiver_error', 'receiver_close' ] emitted by rhea's 'session' object. +55ms
  rhea-promise:session [connection-1] Calling amqp session.begin(). +0ms
  rhea:frames [connection-1]:0 -> begin#11 {"incoming_window":2048,"outgoing_window":4294967295}  +6ms
  rhea:raw [connection-1] SENT: 32 0000002002000000005311d000000010000000044043700000080070ffffffff +6ms
  rhea:io [connection-1] read 34 bytes +6ms
  rhea:io [connection-1] got frame of size 34 +20ms
  rhea:raw [connection-1] RECV: 34 0000002202000000005311c0150560000052017000003fff707fffffff700000ffff +20ms
  rhea:frames [connection-1]:0 <- begin#11 {"next_outgoing_id":1,"incoming_window":16383,"outgoing_window":2147483647,"handle_max":65535}  +20ms
  rhea:events [connection-1] Session got event: session_open +26ms
  rhea-promise:session [connection-1] session got event: 'session_open'. Re-emitting the translated context. +22ms
  rhea-promise:translate [connection-1] Translating the context for event: 'session_open'. +26ms
  rhea-promise:session [connection-1] Resolving the promise with amqp session. +1ms
  rhea-promise:eventhandler [connection-1] rhea-promise 'sender' object is listening for events: [ 'sendable', 'sender_open', 'sender_draining', 'sender_flow', 'sender_error', 'sender_close', 'accepted', 'released', 'rejected', 'modified', 'settled' ] emitted by rhea's 'sender' object. +24ms
  rhea-promise:eventhandler [connection-1] ListenerCount for event 'sender_error' on rhea's 'sender' object is: 1. +1ms
  rhea:frames [connection-1]:0 -> attach#12 {"name":"e986e19c-dcbb-1044-a754-d7e89141c594","source":[],"target":["test"]}  +4ms
  rhea:raw [connection-1] SENT: 87 0000005702000000005312d0000000470000000aa12465393836653139632d646362622d313034342d613735342d6437653839313431633539344342404000532845005329d00000000a00000001a10474657374404043 +4ms
  rhea:io [connection-1] read 108 bytes +7ms
  rhea:io [connection-1] got frame of size 74 +0ms
  rhea:raw [connection-1] RECV: 74 0000004a02000000005312c03d07a12465393836653139632d646362622d313034342d613735342d64376538393134316335393443415002500000532845005329c00701a10474657374 +3ms
  rhea:frames [connection-1]:0 <- attach#12 {"name":"e986e19c-dcbb-1044-a754-d7e89141c594","role":true,"snd_settle_mode":2,"source":[],"target":["test"]}  +3ms
  rhea:events [connection-1] Link got event: sender_open +7ms
  rhea-promise:sender [connection-1] sender got event: 'sender_open'. Re-emitting the translated context. +0ms
  rhea-promise:translate [connection-1] Translating the context for event: 'sender_open'. +7ms
  rhea:io [connection-1] got frame of size 34 +1ms
  rhea:raw [connection-1] RECV: 34 0000002202000000005313c01507437000003fff5201707fffffff434370000003e8 +1ms
  rhea:frames [connection-1]:0 <- flow#13 {"incoming_window":16383,"next_outgoing_id":1,"outgoing_window":2147483647,"link_credit":1000}  +2ms
  rhea:events [connection-1] Link got event: sender_flow +1ms
  rhea-promise:sender [connection-1] sender got event: 'sender_flow'. Re-emitting the translated context. +2ms
  rhea-promise:translate [connection-1] Translating the context for event: 'sender_flow'. +2ms
  rhea:events [connection-1] Link got event: sendable +1ms
  rhea-promise:sender [connection-1] sender got event: 'sendable'. Re-emitting the translated context. +0ms
  rhea-promise:translate [connection-1] Translating the context for event: 'sendable'. +0ms
  rhea-promise:sender [connection-1] Resolving the promise with amqp sender 'e986e19c-dcbb-1044-a754-d7e89141c594'. +0ms
sender1 is open
opening receiver1
  rhea-promise:eventhandler [connection-1] rhea-promise 'session' object is listening for events: [ 'session_open', 'session_error', 'session_close', 'settled', 'sender_error', 'sender_close', 'receiver_error', 'receiver_close' ] emitted by rhea's 'session' object. +7ms
  rhea-promise:session [connection-1] Calling amqp session.begin(). +9ms
  rhea:frames [connection-1]:1 -> begin#11 {"incoming_window":2048,"outgoing_window":4294967295}  +3ms
  rhea:raw [connection-1] SENT: 32 0000002002000001005311d000000010000000044043700000080070ffffffff +4ms
  rhea:io [connection-1] read 34 bytes +4ms
  rhea:io [connection-1] got frame of size 34 +0ms
  rhea:raw [connection-1] RECV: 34 0000002202000001005311c0150560000152017000003fff707fffffff700000ffff +0ms
  rhea:frames [connection-1]:1 <- begin#11 {"remote_channel":1,"next_outgoing_id":1,"incoming_window":16383,"outgoing_window":2147483647,"handle_max":65535}  +1ms
  rhea:events [connection-1] Session got event: session_open +3ms
  rhea-promise:session [connection-1] session got event: 'session_open'. Re-emitting the translated context. +2ms
  rhea-promise:translate [connection-1] Translating the context for event: 'session_open'. +3ms
  rhea-promise:session [connection-1] Resolving the promise with amqp session. +0ms
  rhea-promise:eventhandler [connection-1] rhea-promise 'receiver' object is listening for events: [ 'message', 'receiver_open', 'receiver_drained', 'receiver_flow', 'receiver_error', 'receiver_close', 'settled' ] emitted by rhea's 'receiver' object. +4ms
  rhea-promise:eventhandler [connection-1] ListenerCount for event 'receiver_error' on rhea's 'receiver' object is: 1. +0ms
  rhea:frames [connection-1]:1 -> attach#12 {"name":"14dd75a4-1830-bd4e-9794-8c8ee5f4e3ba","role":true,"source":[null,null,null,null,true],"target":[]}  +2ms
  rhea:raw [connection-1] SENT: 83 0000005302000001005312d00000004300000007a12431346464373561342d313833302d626434652d393739342d38633865653566346533626143414040005328d00000000900000005404040404100532945 +3ms
  rhea:io [connection-1] read 192 bytes +16ms
  rhea:io [connection-1] got frame of size 192 +1ms
  rhea:raw [connection-1] RECV: 192 000000c002000001005312c0b30aa12431346464373561342d313833302d626434652d393739342d386338656535663465336261434250025000005328c07a0ba13774656d702d71756575653a2f2f49443a4330325451324a30485444362d36343834352d313533383136353132343431362d333a33323a3043a30b73657373696f6e2d656e644341c11602a30f6c69666574696d652d706f6c69637900532b4540404040e01201a30f74656d706f726172792d717565756500532945404243 +14ms
  rhea:frames [connection-1]:1 <- attach#12 {"name":"14dd75a4-1830-bd4e-9794-8c8ee5f4e3ba","snd_settle_mode":2,"source":["temp-queue://ID:C02TQ2J0HTD6-64845-1538165124416-3:32:0",0,"session-end",0,true,["lifetime-policy",[]],null,null,null,null,["temporary-queue"]],"target":[]}  +14ms
  rhea:events [connection-1] Link got event: receiver_open +16ms
  rhea-promise:receiver [connection-1] receiver got event: 'receiver_open'. Re-emitting the translated context. +0ms
  rhea-promise:translate [connection-1] Translating the context for event: 'receiver_open'. +16ms
  rhea-promise:receiver [connection-1] Resolving the promise with amqp receiver '14dd75a4-1830-bd4e-9794-8c8ee5f4e3ba'. +1ms
  rhea:frames [connection-1]:1 -> flow#13 {"incoming_window":2048,"outgoing_window":4294967295,"link_credit":1000}  +1ms
  rhea:raw [connection-1] SENT: 39 0000002702000001005313d000000017000000074370000008004370ffffffff434370000003e8 +1ms
receiver1 is open
  rhea-promise:connection [connection-2] Trying to create a new amqp connection. +54ms
  rhea:io [connection-2] connected 127.0.0.1:58855 -> 127.0.0.1:5672 +13ms
  rhea:frames [connection-2] -> { protocol_id: 3, major: 1, minor: 0, revision: 0 } +13ms
  rhea:io [connection-2] read 42 bytes +7ms
  rhea:frames [connection-2] <- { protocol_id: 3, major: 1, minor: 0, revision: 0 } +7ms
  rhea:io [connection-2] got frame of size 34 +1ms
  rhea:raw [connection-2] RECV: 34 0000002202010000005340c01501e01202a305504c41494e09414e4f4e594d4f5553 +20ms
  rhea:frames [connection-2]:0 <- sasl_mechanisms#40 {"sasl_server_mechanisms":["PLAIN","ANONYMOUS"]}  +0ms
  rhea:frames [connection-2]:0 -> sasl_init#41 {"mechanism":"PLAIN","initial_response":{"type":"Buffer","data":[0,103,117,101,115,116,0,103,117,101,115,116]},"hostname":"localhost"}  +0ms
  rhea:raw [connection-2] SENT: 52 0000003402010000005341d00000002400000003a305504c41494ea00c006775657374006775657374a1096c6f63616c686f7374 +0ms
  rhea:io [connection-2] read 16 bytes +1ms
  rhea:io [connection-2] got frame of size 16 +0ms
  rhea:raw [connection-2] RECV: 16 0000001002010000005344c003015000 +1ms
  rhea:frames [connection-2]:0 <- sasl_outcome#44 {}  +1ms
  rhea:frames [connection-2] -> { protocol_id: 0, major: 1, minor: 0, revision: 0 } +0ms
  rhea:frames [connection-2]:0 -> open#10 {"username":"guest","password":"guest","host":"localhost","port":5672,"operationTimeoutInSeconds":60,"id":"connection-2","container_id":"920ac558-868c-c349-9181-f57a1e864bfb"}  +0ms
  rhea:raw [connection-2] SENT: 58 0000003a02000000005310d00000002a00000001a12439323061633535382d383638632d633334392d393138312d663537613165383634626662 +20ms
  rhea:io [connection-2] read 8 bytes +20ms
  rhea:frames [connection-2] <- { protocol_id: 0, major: 1, minor: 0, revision: 0 } +20ms
  rhea:io [connection-2] read 255 bytes +0ms
  rhea:io [connection-2] got frame of size 72 +0ms
  rhea:raw [connection-2] RECV: 72 0000004802000000005310c03b0aa100407000020000607fff4040404040c12802a324616d71703a636f6e6e656374696f6e2d65737461626c6973686d656e742d6661696c656441 +0ms
  rhea:frames [connection-2]:0 <- open#10 {"max_frame_size":131072,"channel_max":32767,"properties":{"amqp:connection-establishment-failed":true}}  +0ms
  rhea:events [connection-2] Connection got event: connection_open +42ms
  rhea-promise:connection [connection-2] connection got event: 'connection_open'. Re-emitting the translated context. +41ms
  rhea-promise:translate [connection-2] Translating the context for event: 'connection_open'. +43ms
  rhea-promise:connection [connection-2] Resolving the promise with amqp connection. +1ms
  rhea:io [connection-2] got frame of size 183 +1ms
  rhea:raw [connection-2] RECV: 183 000000b702000000005318c0aa0100531dc0a403a312616d71703a696e76616c69642d6669656c64a16d42726f6b65723a206c6f63616c686f7374202d20436c69656e743a2039323061633535382d383638632d633334392d393138312d66353761316538363462666220616c726561647920636f6e6e65637465642066726f6d207463703a2f2f3132372e302e302e313a3538383534c11e02a30d696e76616c69642d6669656c64a30c636f6e7461696e65722d6964 +1ms
  rhea:frames [connection-2]:0 <- close#18 {"error":{"condition":"amqp:invalid-field","description":"Broker: localhost - Client: 920ac558-868c-c349-9181-f57a1e864bfb already connected from tcp://127.0.0.1:58854","info":{"invalid-field":"container-id"}}}  +1ms
  rhea:events [connection-2] Connection got event: connection_error +1ms
  rhea-promise:connection [connection-2] connection got event: 'connection_error'. Will re-emit in the next tick. +0ms
  rhea:events [connection-2] Connection got event: connection_close +0ms
  rhea-promise:connection [connection-2] connection got event: 'connection_close'. Re-emitting the translated context. +0ms
  rhea-promise:translate [connection-2] Translating the context for event: 'connection_close'. +0ms
  rhea:frames [connection-2]:0 -> close#18 {}  +1ms
  rhea:raw [connection-2] SENT: 12 0000000c0200000000531845 +1ms
opening receiver2
  rhea-promise:eventhandler [connection-2] rhea-promise 'session' object is listening for events: [ 'session_open', 'session_error', 'session_close', 'settled', 'sender_error', 'sender_close', 'receiver_error', 'receiver_close' ] emitted by rhea's 'session' object. +58ms
  rhea-promise:session [connection-2] Calling amqp session.begin(). +60ms
  rhea:frames [connection-2]:0 -> begin#11 {"incoming_window":2048,"outgoing_window":4294967295}  +1ms
  rhea:raw [connection-2] SENT: 32 0000002002000000005311d000000010000000044043700000080070ffffffff +1ms
  rhea-promise:connection [connection-2] connection got event: 'connection_error'. Re-emitting the translated context. +2ms
  rhea-promise:translate [connection-2] Translating the context for event: 'connection_error'. +2ms
  rhea:frames [connection-1]:0 -> empty +7s
  rhea:raw [connection-1] SENT: 8 0000000802000000 +7s
  rhea:frames [connection-1]:0 -> empty +8s
  rhea:raw [connection-1] SENT: 8 0000000802000000 +8s
```

By using the debug I found out that the connection object is emitting `connection_error`, so I added a handler for that and I found this:

```
'Broker: localhost - Client: 6b2b300a-e389-e245-babc-de9b440a7ff5 already connected from tcp://127.0.0.1:58869',
```

I will investigate this, maybe my activemq has a limit of connections per client set to 1, or something like that?

**Comment by amarzavery** [comment]
Each connection has a different id. "connection-1", "connection-2", etc. Yes the container remains the same. This is because, rhea exports a single instance of the container as the only thing from the package. It is the default container. By default connection would be created on the default container instance exported by rhea. Different Azure services like Service Bus and EventHubs support multiple connections on the same container from the client. 
If active mq does not support this, then creating a container before creating the connection makes sense.

**Comment by jfromaniello** [comment]
@amarzavery thank you very much for your kind help, closing this now

**Comment by amarzavery** [comment]
@jfromaniello - Please take a look at [this comment](https://github.com/amqp/rhea/issues/140#issuecomment-426369484) from @grs in rhea. It is always good to create different container objects for your use case. However, you can also specify the `container_id` option in the `connectionOptions`. This should indicate the service that the connection is coming from a different container/process and things should work as expected.

**Comment by swilliams-a3digital** [comment]
I ran into the same issue with ActiveMQ.  I was very happy to see how to fix it here.    I confirmed the setting container_id to a uuid in connectionOptions also resolves the issue.
