### ISSUE TITLE
The error on the connection forces the process to crash?  And other issues.

### ISSUE THREAD

**Issue by System233** [amqp/rhea-promise#117]
**Describe the bug**

This is my first time trying AMQP 1.0, and I'm using rhea with RabbitMQ 4.0.5. I've tested both classic and quorum queues, and I encounter the following issues:

1. The error on the connection causes the process to freeze. Even after catching the exception with `process.on('uncaughtException')`, the process cannot recover from the error.

```ts
      options: {  //createReceiver options
        source: STAT_QUEUE_ADDR,
        autoaccept: false, //no effect. not working
        autosettle: false, 
        onError(ctx) {  //not working ,got Error [ERR_UNHANDLED_ERROR]: Unhandled error. and hang process
           console.log('onError', ctx.message);
        },
        // onMessage(ctx) {
        //   console.log('onMessage', ctx.message);
        //   ctx.delivery?.reject();
        // },
      },
      
      process.on('uncaughtException')` //not working ,got Error [ERR_UNHANDLED_ERROR]: Unhandled error. and hang process

      conn.on(rhea.ConnectionEvents.connectionError, opts.errorHandler); //not working ,got Error [ERR_UNHANDLED_ERROR]: Unhandled error. and hang process
      conn.on("error" as any, opts.errorHandler); //working , error caught

//--------------------------------------------------------------------

    this.sender.on(SenderEvents.rejected, (context) => {
      console.log('rejected', context.message);
    });
    this.sender.on(SenderEvents.accepted, (context) => {
      console.log('accepted', context.message);
    });
    this.sender.on(SenderEvents.settled, (context) => {
      console.log('settled', context.message);
    });
    this.receiver.on(ReceiverEvents.message, (context: EventContext) => {
      console.log('message', context.message?.message_annotations);
      // throw new Error('fawf');   //nack working 
      context.delivery!.modified({}); <<<<<<<<<<<//GOT RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= 0 and <= 4294967295. Received
      //context.delivery!.reject({}); //nack not working
    });
```
context.delivery!.modified({}); 
```log
>>>>>>>>  context.delivery!.modified({}); <<<<<<
  _context: RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= 0 and <= 4294967295. Received 4_294_967_542
      at checkInt (node:internal/buffer:74:11)
      at writeU_Int32BE (node:internal/buffer:804:3)
      at Buffer.writeUInt32BE (node:internal/buffer:817:10)
      at TypeDesc.write (**\node_modules\rhea\lib\types.js:180:60)
      at types.Writer.write_fixed_width (**\node_modules\rhea\lib\types.js:780:14)
      at types.Writer.write_value (**\node_modules\rhea\lib\types.js:826:14)      
      at types.Writer.write (**\node_modules\rhea\lib\types.js:818:14)
      at types.Writer.write_compound (**\node_modules\rhea\lib\types.js:853:18)   
      at types.Writer.write_value (**\node_modules\rhea\lib\types.js:830:14)      
      at types.Writer.write (**\node_modules\rhea\lib\types.js:818:14) {
    code: 'ERR_OUT_OF_RANGE'
  },
```

~~It’s possible to achieve something similar to nack by throwing an exception in the message handler, but this is quite inelegant and cannot handle asynchronous callbacks.~~
This is actually an infinite reconnection. It is still unacceptable for the exception in the handler to directly cause the entire client to be disconnected.

Additionally, there are several other problems:

1. When passing a URL with a username and password via path for the connection, a `SASL layer not enabled` exception is raised. This is because the `username/password` fields or the unpublished `sasl_mechanisms` option were not provided. `Connection.get_option();` should be able to extract the `username` and `password` from the URL.
2. Calling `createSender` or `createReceiver` with an empty `{}` option causes the process to freeze. RabbitMQ logs show numerous warnings.  
   When specifying a non-existent queue (e.g., `/queues/log`) with a RabbitMQ v2 address, the process freezes, and the RabbitMQ logs show a lot of warnings.
3. There is a hidden `error` event on the connection that is not exposed. Adding the `error` event directly to the connection causes TypeScript errors. However, exceptions on the receiver are emitted as `error` events to the connection. None of the `xxxEvents.xxxError` listeners on the `connection/sender/receiver` can handle this error.

**Comment by jeremymeng** [comment]
@System233 are you using `rhea` or `rhea-promise`?

**Comment by System233** [comment]
Incompatible with rabbitmq4, operation timeout at any time due to unhandled protocol errors. fallback to amqplib.

**Comment by System233** [comment]
a
