### ISSUE TITLE
Unable to send more than 10 messages at same time.

### ISSUE THREAD

**Issue by anzileiro** [amqp/rhea-promise#73]
**Describe the bug**
When I was trying to send 10 messages to the ActiveMQ using this lib I was getting this message warning:

```terminal
(node:32616) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connection_open listeners added to [Connection]. Use emitter.setMaxListeners() to increase limit
(node:32616) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connection_close listeners added to [Connection]. Use emitter.setMaxListeners() to increase limit
(node:32616) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 disconnected listeners added to [Connection]. Use emitter.setMaxListeners() to increase limit
(node:32616) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 disconnected listeners added to [Connection]. Use emitter.setMaxListeners() to increase limit
```

And when I try to send 100 messages I'm getting this message error:

```terminal
(node:32634) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connection_open listeners added to [Connection]. Use emitter.setMaxListeners() to increase limit
(node:32634) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connection_close listeners added to [Connection]. Use emitter.setMaxListeners() to increase limit
(node:32634) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 disconnected listeners added to [Connection]. Use emitter.setMaxListeners() to increase limit
(node:32634) UnhandledPromiseRejectionWarning: Error: read ECONNRESET
    at Handle.execute (/Users/anzileiro/projects/node/beetech/hubspot-routine/src/domain/process/use-case/Handle.ts:21:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:32634) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:32634) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**To Reproduce**

- Get the example present in this repository documentation and try to send 100 messages inside a Promise.All.

**Expected behavior**
- To send to the ActiveMQ all messages without any error. 

**Package-version**: 1.0.0
**node.js version**: 12.18.3
**OS name and version**: MacOS Catalina 10.15.7

**Additional context**

The code is:

```javascript
  const promises = await Promise.all(customers.map(async (item) => {
        const processor = await publisherProcess.execute(item); // this send message.
        return processor.getResult(); // this get the delivery status.
      }));
```

**Comment by ps2goat** [comment]
Are you creating a new connection each time? You should just have one that you reuse.

**Comment by sunil-rnl** [comment]
@anzileiro Can you pls share how you implemented this. I'm also running into same issue. How you resued the existing connection. If you can share the sample code that would be helpful. Thanks
